version: "3.8"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: R00t!
      MYSQL_DATABASE: labdb
      MYSQL_USER: am-eskandari
      MYSQL_PASSWORD: 2314
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: ./web
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
